spring:
  config:
    activate:
      on-profile: prod
  application:
    name: authentication-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://db:3306/authentication
    username: user
    password: password
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}
        health-check-critical-timeout: 10m

server:
  port: 0

jwt:
  secret: secret
  expiration: 1000
  prefix: 'Bearer '

---
spring:
  config:
    activate:
      on-profile: dev
  application:
    name: authentication-service
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: user
    password: password
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instance-id: ${spring.application.name}-${spring.cloud.client.hostname}
        health-check-critical-timeout: 10m

server:
  port: 8901
  error:
    include-message: always

jwt:
  secret: secret
  expiration: 1000
  prefix: 'Bearer '
