version: '3'

services:
  consul:
    image: consul
    volumes:
      - ./consul/config:/consul/config
      - ./consul/data:/consul/data
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    command: "agent -server -client 0.0.0.0 -ui -bootstrap-expect 1"

  db:
    image: mariadb:10.7
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d/:ro
    environment:
      - MARIADB_DATABASE=root
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_USER=user
      - MARIADB_PASSWORD=password
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management-alpine
    volumes:
      - ./rabbitmq/data:/var/lib/rabbitmq/
      - ./rabbitmq/log:/var/log/rabbitmq/
    ports:
      - "5672:5672"
      - "15672:15672"

  gateway-service:
    image: ${DOCKER_REGISTRY_URL}/ecommerce-microservices/gateway:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BPL_JAVA_NMT_ENABLED=false
    ports:
      - "8900:8900"
    depends_on:
      - consul

  authentication-service:
    image: ${DOCKER_REGISTRY_URL}/ecommerce-microservices/authentication:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BPL_JAVA_NMT_ENABLED=false
    depends_on:
      - consul
      - db

  user-service:
    image: ${DOCKER_REGISTRY_URL}/ecommerce-microservices/user:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BPL_JAVA_NMT_ENABLED=false
    depends_on:
      - consul
      - db

  product-service:
    image: ${DOCKER_REGISTRY_URL}/ecommerce-microservices/product:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BPL_JAVA_NMT_ENABLED=false
    depends_on:
      - consul
      - db

  order-service:
    image: ${DOCKER_REGISTRY_URL}/ecommerce-microservices/order:0.0.1-SNAPSHOT
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BPL_JAVA_NMT_ENABLED=false
    depends_on:
      - consul
      - db
